# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17ongM44B8BCXtmoZIuMY1ISuEh5gVoIA
"""

import random as rand 
import matplotlib.pyplot as plt
import numpy as np

#P1 is power of 10 in 10^99 and P2 is power of 10 in 10^96
P1=99
P2=96
# conducting the experiment for 1000000 times 
sim_len=1000000
i=0
# c stands for count
c=0
while (i<sim_len):
  # creating a peir (x,y) such that both 0<= x,y <=99
  x=rand.randint(0,P1)
  y=rand.randint(0,P1)
  # we only need the numbers which are multiples of 10^96 and divisors 0f 10^99
  if (x>=P2 and y>=P2):
    c+=1
  i+=1

p=c/sim_len

print ("The Probability obtaine by simulation is ", p)
print ("The probability obtained by calculation is =1/625=0.0016")



X = [1,2]
Y = [p, 1/625]
LABELS = ["Prob by simulation", "Prob by calculation"]

plt.bar(X, Y,color='b', align='center')
plt.xticks(X, LABELS)


plt.show()